import type { Movie, Genre } from "@/types/movie";

// Mock dataset used as a graceful fallback when no backend is available.
// Real API calls are still wired through axios in movieApi.ts.

export const GENRES: Genre[] = [
  { id: 1, name: "Trending Now" },
  { id: 2, name: "Action & Adventure" },
  { id: 3, name: "Sci-Fi & Fantasy" },
  { id: 4, name: "Drama" },
  { id: 5, name: "Comedies" },
];

const img = (seed: string, w = 600, h = 900) =>
  `https://picsum.photos/seed/${seed}/${w}/${h}`;

export const MOCK_MOVIES: Movie[] = [
  {
    id: 1,
    title: "Neon Horizon",
    description:
      "In a sprawling neon city, a rogue hacker uncovers a conspiracy that could rewrite reality itself.",
    release_date: "2024-09-12",
    genres: [GENRES[0], GENRES[2]],
    thumbnail: img("neon", 600, 900),
    backdrop: img("neon-bd", 1920, 1080),
    video_file: "dQw4w9WgXcQ",
    rating: 8.4,
  },
  {
    id: 2,
    title: "Iron Pulse",
    description: "A retired soldier returns for one final, impossible mission.",
    release_date: "2023-04-21",
    genres: [GENRES[1]],
    thumbnail: img("iron", 600, 900),
    backdrop: img("iron-bd", 1920, 1080),
    video_file: "5qap5aO4i9A",
    rating: 7.8,
  },
  {
    id: 3,
    title: "Echoes of Tomorrow",
    description: "A scientist discovers messages from her future self.",
    release_date: "2025-01-08",
    genres: [GENRES[2], GENRES[3]],
    thumbnail: img("echoes", 600, 900),
    video_file: "9bZkp7q19f0",
    rating: 9.0,
  },
  {
    id: 4,
    title: "Midnight Avenue",
    description: "Two strangers cross paths on a night that changes everything.",
    release_date: "2022-11-04",
    genres: [GENRES[3]],
    thumbnail: img("midnight", 600, 900),
    video_file: "L_jWHffIx5E",
    rating: 7.2,
  },
  {
    id: 5,
    title: "Laugh Track",
    description: "A struggling comedian gets one impossible shot at the big stage.",
    release_date: "2024-02-14",
    genres: [GENRES[4]],
    thumbnail: img("laugh", 600, 900),
    video_file: "kJQP7kiw5Fk",
    rating: 7.6,
  },
  {
    id: 6,
    title: "Crimson Sky",
    description: "An ace pilot defends the last free city from above.",
    release_date: "2023-07-30",
    genres: [GENRES[1], GENRES[0]],
    thumbnail: img("crimson", 600, 900),
    video_file: "fJ9rUzIMcZQ",
    rating: 8.1,
  },
  {
    id: 7,
    title: "The Quiet Algorithm",
    description: "An AI begins to dream — and someone is listening.",
    release_date: "2025-03-22",
    genres: [GENRES[2]],
    thumbnail: img("algo", 600, 900),
    video_file: "hY7m5jjJ9mM",
    rating: 8.7,
  },
  {
    id: 8,
    title: "Salt & Stars",
    description: "A coastal town holds a secret that draws travelers from afar.",
    release_date: "2024-06-18",
    genres: [GENRES[3], GENRES[0]],
    thumbnail: img("salt", 600, 900),
    video_file: "OPf0YbXqDm0",
    rating: 7.4,
  },
  {
    id: 9,
    title: "Velvet Heist",
    description: "The greatest crew. The greatest score. One impossible night.",
    release_date: "2023-12-01",
    genres: [GENRES[1], GENRES[4]],
    thumbnail: img("velvet", 600, 900),
    video_file: "RgKAFK5djSk",
    rating: 8.0,
  },
  {
    id: 10,
    title: "Paper Kingdoms",
    description: "Two rival publishers fight for the soul of a dying industry.",
    release_date: "2022-08-19",
    genres: [GENRES[3]],
    thumbnail: img("paper", 600, 900),
    video_file: "uelHwf8o7_U",
    rating: 7.0,
  },
  {
    id: 11,
    title: "Orbit Bound",
    description: "A crew of misfits is humanity's last hope beyond the stars.",
    release_date: "2025-05-09",
    genres: [GENRES[2], GENRES[1]],
    thumbnail: img("orbit", 600, 900),
    backdrop: img("orbit-bd", 1920, 1080),
    video_file: "ktvTqknDobU",
    rating: 9.2,
  },
  {
    id: 12,
    title: "Sunset Protocol",
    description: "Spies, lies and a dossier that could end nations.",
    release_date: "2024-10-27",
    genres: [GENRES[1]],
    thumbnail: img("sunset", 600, 900),
    video_file: "JGwWNGJdvx8",
    rating: 7.9,
  },
];
