# Generated by Django 6.0.2 on 2026-05-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='best', max_length=255),
            preserve_default=False,
        ),
    ]
